name: Algolia Reindex

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  algolia:
    runs-on: ubuntu-latest
    steps:
      - name: Algolia Crawler Automatic Crawl
        uses: algolia/algoliasearch-crawler-github-actions@v1.1.0
        with:
          github-token: ${{ secrets.ACCESS_TOKEN }}
          crawler-name: 'jonas-notes'
          crawler-user-id: 'ff914b30-c55c-4242-b0ff-ad463ae88a26'
          crawler-api-key: '8eca7ef2aa0f9dba872ed4989a42b84f'
          algolia-app-id: '5C1C4WHDZM'
          algolia-api-key: '52536ffcb312e563b17420314960a6ad'
          site-url: 'https://notes.web025.cn'
