name: Algolia Reindex

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  algolia:
    runs-on: ubuntu-latest
    steps:
      - name: Algolia Crawler Automatic Crawl
        uses: algolia/algoliasearch-crawler-github-actions@v1.1.0
        with:
          github-token: ${{ secrets.ACCESS_TOKEN }}
          algolia-app-id: ${{ secrets.ALGOLIA_APP_ID }}
          algolia-api-key: ${{ secrets.ALGOLIA_SEARCH_API_KEY }}
          site-url: 'https://notes.web025.cn'
